CREATE DATABASE IF NOT EXISTS diretoria
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE diretoria;

CREATE TABLE IF NOT EXISTS turno (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	horario VARCHAR(10) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS cursos (
	id VARCHAR(10) PRIMARY KEY,
	nome VARCHAR(20),
	turno_id BIGINT UNSIGNED REFERENCES turno(id)
);
CREATE TABLE IF NOT EXISTS comodos (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	comodo VARCHAR(20) UNIQUE NOT NULL

);
CREATE TABLE IF NOT EXISTS areas_administrativas (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) UNIQUE NOT NULL,
	descricao TEXT
);
CREATE TABLE IF NOT EXISTS usuarios (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	apelido VARCHAR(20) UNIQUE NOT NULL,
	ano_ingresso INT NOT NULL,
	curso_id VARCHAR(10) NOT NULL REFERENCES cursos(id),
	comodo_id BIGINT UNSIGNED NOT NULL REFERENCES comodos(id),
	senha_salted_hashed VARCHAR(255) NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_ultima_modificacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS usuario_areas ( -- tabela associativa n:n
    usuario_id BIGINT UNSIGNED NOT NULL,
    area_adm_id BIGINT UNSIGNED,
    PRIMARY KEY (usuario_id, area_adm_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (area_adm_id) REFERENCES areas_administrativas(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS venda_salgado (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	data DATE UNIQUE NOT NULL,
	valor_gasto DECIMAL(10,2) NOT NULL,
	valor_recebido DECIMAL(10,2) NOT NULL,
	observacao TEXT,
	venda_ocorreu BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS vendedores_salgado (
	venda_salgado_id BIGINT UNSIGNED NOT NULL,
    usuario_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (venda_salgado_id, usuario_id),
    FOREIGN KEY (venda_salgado_id) REFERENCES venda_salgado(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
